# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np
res = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
print(res[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [21]:
print('Второй столбец: среднее значение:{}, минимум:{}, максимум:{}, медиана:{}'.format(np.mean(res[:,1]),np.min(res[:,1]),np.max(res[:,1]),np.median(res[:,1])))
print('Третий столбец: среднее значение:{}, минимум:{}, максимум:{}, медиана:{}'.format(np.mean(res[:,2]),np.min(res[:,2]),np.max(res[:,2]),np.median(res[:,2])))

Второй столбец: среднее значение:21601.00648, минимум:1, максимум:2147483647, медиана:40.0
Третий столбец: среднее значение:9.05528, минимум:1, максимум:39, медиана:9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [3]:
print(res[res[:,1]<= np.quantile(res[:,1],0.75)])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [4]:
print('Кол-во рецептов, для которых продолжительность рецептов равна нулю:',res[res[:,1]== 0].shape[0])
res[res[:,1] == 0,1] = 1
print('Кол-во после замены:',res[res[:,1]== 0].shape[0])


Кол-во рецептов, для которых продолжительность рецептов равна нулю: 479
Кол-во после замены: 0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [5]:
print(len(np.unique(res[:,0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [22]:
print('Кол-во различных значений: {}\n Сами значения:{}'.format(len(np.unique(res[:,2])),np.unique(res[:,2])))

Кол-во различных значений: 37
 Сами значения:[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [6]:
print(res[res[:,2]<=5])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [7]:
res1 = res[:,2]/res[:,1]
print('Максимальное:', np.max(res1))
print(res1)


Максимальное: 24.0
[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [8]:
res1 = res[np.argsort(res[:,1])][-100:,2]
print(np.mean(res1))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [9]:
print(res[np.random.randint(res.shape[0], size = 10)])

[[230691     55      6]
 [ 54152     30      6]
 [443792     38      9]
 [ 84472     17      6]
 [527417     40     11]
 [306991     50      9]
 [ 22059     60      7]
 [154619     40     10]
 [358641     95      5]
 [ 35446     15      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [10]:
res1 = (res[res[:,2]< np.mean(res[:,2])].shape[0]/res.shape[0])*100
print(res1)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [14]:
res_ans = (res[:,1] <= 20) & (res[:,2]<=5)
print(np.hstack((res, res_ans[:, np.newaxis])))

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [16]:
ans = np.hstack((res, res_ans[:, np.newaxis]))
print(ans[ans[:,3] == 1].shape[0] / res.shape[0]*100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [19]:
res1_1 = res[res[:,1] < 10]
res2_2 = res[(res[:,1] >= 10) & (res[:,1] < 20)]
res3_3 = res[res[:,1] >= 20]
ans1 = min(res1_1.shape[0],res2_2.shape[0],res3_3.shape[0])
ans_ans = np.array([res1_1[:ans1],res2_2[:ans1],res3_3[:ans1]])
print('Размерность:',ans_ans.shape)
print(ans_ans)

Размерность: (3, 7588, 3)
[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      1      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
